services:
  life-calendar-bot:
    build: .
    env_file:
      - .env
    environment:
      MPLCONFIGDIR:   /tmp/mplcache
      LIFE_BOT_TOKEN: ${LIFE_BOT_TOKEN}
      DATABASE_URL:   ${DATABASE_URL:-postgresql://postgres:postgres@db:5432/life}
      COMMUNITY_ID:   ${COMMUNITY_ID}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
    restart: unless-stopped
